# 服务端口
server:
  port: 1003

# 注册application才需要用到,如果不需要往注册中心注册,则下属配置可以不写,推荐写上
spring:
  application:
    name: ms-provider-1003
# 数据源相关配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 286393118

# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka

