CREATE TABLE `USER_BASIC_INFO` (
  `ID` int(11) NOT NULL COMMENT '主键',
  `NAME` varchar(50) NOT NULL unique key COMMENT '名称',
  `AGE` int(3) NOT NULL COMMENT '年龄',
  `CTIME` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
